name: chatty_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  image_picker: ^1.1.0
  firebase_storage: ^12.0.6
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1


  # Firebase dependencies
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true

  


flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/default_profile.jpg
    - assets/images/logo.png
