// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoyXqXVnKlv_Mxevq3TWB4VlpPCvNqhM8',
    appId: '1:528583646731:web:4170db12ae3d27fb08710e',
    messagingSenderId: '528583646731',
    projectId: 'chattyapp-ff181',
    authDomain: 'chattyapp-ff181.firebaseapp.com',
    storageBucket: 'chattyapp-ff181.firebasestorage.app',
    measurementId: 'G-LJVT3W0XMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWbY9R8XdMfIAtetazlOpr7T-_2eU4JiA',
    appId: '1:528583646731:android:c1f66be2f1bf788708710e',
    messagingSenderId: '528583646731',
    projectId: 'chattyapp-ff181',
    storageBucket: 'chattyapp-ff181.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0mSo6IzEMcBEAlHjXcTmGf8ftxg5XNZ8',
    appId: '1:528583646731:ios:2ee4dedee6904e1c08710e',
    messagingSenderId: '528583646731',
    projectId: 'chattyapp-ff181',
    storageBucket: 'chattyapp-ff181.firebasestorage.app',
    iosBundleId: 'com.example.chattyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0mSo6IzEMcBEAlHjXcTmGf8ftxg5XNZ8',
    appId: '1:528583646731:ios:2ee4dedee6904e1c08710e',
    messagingSenderId: '528583646731',
    projectId: 'chattyapp-ff181',
    storageBucket: 'chattyapp-ff181.firebasestorage.app',
    iosBundleId: 'com.example.chattyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoyXqXVnKlv_Mxevq3TWB4VlpPCvNqhM8',
    appId: '1:528583646731:web:e1f38b0352d185e208710e',
    messagingSenderId: '528583646731',
    projectId: 'chattyapp-ff181',
    authDomain: 'chattyapp-ff181.firebaseapp.com',
    storageBucket: 'chattyapp-ff181.firebasestorage.app',
    measurementId: 'G-TDKSPPF7E4',
  );

}